---
version: '3.4'
services:

  besu_validator01:
    build:
      context: besu/.
    image: vbvb/besu_validator01
    entrypoint: /opt/besu/bin/besu --config-file=/config/config.toml 
    volumes:
      - ./besu/config/validator01/key01:/opt/besu/data/key01
      - ./besu/config/validator01/config.toml:/config/config.toml
    ports:
      - 30303:30303/tcp
      - 30303:30303/udp
      - 8545:8545
      - 8546:8546
      - 8547:8547
      - 9545:9545
  
  startstop_validator01:
    build:
      context: start_stop/.
    image: vbvb/startstop_validator01
    entrypoint: nodejs main.js
    environment:
      - STST_URL=http://172.17.0.1:8545
      - STST_INTERVAL=1000
    depends_on:
      - "besu_validator01"

  eth_console:
    build:
      context: eth_console/.
    image: vbvb/eth_console
    volumes:
      - ./eth_console/WALLET.SEC:/console/eth-rpl-console/WALLET.SEC
      - ./eth_console/CONFIG.DAT:/console/eth-rpl-console/CONFIG.DAT
    ports:
      - "9000:22"
