---
version: '3.4'
services:

  besu_validator01:
    build:
      context: validator01/.
    image: vbvb/besu_validator01
    hostname: besu_validator01
    domainname: besu_validator01.local
    entrypoint: /opt/besu/bin/besu --config-file=/config/config.toml 
    volumes:
      - ./validator01/config/key01:/opt/besu/data/key01
      - ./validator01/config/config.toml:/config/config.toml
    ports:
      - 30303:30303/tcp
      - 30303:30303/udp
      - 18545:8545
      - 18546:8546
      - 18547:8547
      - 19545:9545

  besu_validator02:
    build:
      context: validator02/.
    image: vbvb/besu_validator02
    hostname: besu_validator02
    domainname: besu_validator02.local
    entrypoint: /opt/besu/bin/besu --config-file=/config/config.toml 
    volumes:
      - ./validator02/config/key02:/opt/besu/data/key02
      - ./validator02/config/config.toml:/config/config.toml
    ports:
      - 40303:30303/tcp
      - 40303:30303/udp
      - 28545:8545
      - 28546:8546
      - 28547:8547
      - 29545:9545
    depends_on:
      - "besu_validator01"
  
  besu_validator03:
    build:
      context: validator03/.
    image: vbvb/besu_validator03
    hostname: besu_validator03
    domainname: besu_validator03.local
    entrypoint: /opt/besu/bin/besu --config-file=/config/config.toml 
    volumes:
      - ./validator03/config/key03:/opt/besu/data/key03
      - ./validator03/config/config.toml:/config/config.toml
    ports:
      - 50303:30303/tcp
      - 50303:30303/udp
      - 38545:8545
      - 38546:8546
      - 38547:8547
      - 39545:9545
    depends_on:
      - "besu_validator02"
  
  startstop_validator01:
    build:
      context: start_stop/.
    image: vbvb/startstop_validator
    entrypoint: nodejs main.js
    environment:
      - STST_URL=http://besu_validator01:8545
      - STST_INTERVAL=1000
      - STST_VALIDATION_TIMES=10
    depends_on:
      - "besu_validator01"
  
  startstop_validator02:
    build:
      context: start_stop/.
    image: vbvb/startstop_validator
    entrypoint: nodejs main.js
    environment:
      - STST_URL=http://besu_validator02:8545
      - STST_INTERVAL=1000
      - STST_VALIDATION_TIMES=10
    depends_on:
      - "besu_validator02"

  startstop_validator03:
    build:
      context: start_stop/.
    image: vbvb/startstop_validator
    entrypoint: nodejs main.js
    environment:
      - STST_URL=http://besu_validator03:8545
      - STST_INTERVAL=1000
      - STST_VALIDATION_TIMES=10
    depends_on:
      - "besu_validator03"

  eth_console:
    build:
      context: eth_console/.
    image: vbvb/eth_console
    volumes:
      - ./eth_console/WALLET.SEC:/console/eth-rpl-console/WALLET.SEC
      - ./eth_console/CONFIG.DAT:/console/eth-rpl-console/CONFIG.DAT
    ports:
      - "9000:22"
